version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coqui_tts_app
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - .env
